# chapter1.PyTorch基礎知識

In [ ]:
import torch

In [ ]:
z = torch.Tensor(4,5)
z

tensor([[-5.1603e+02,  1.8665e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
z.dtype

torch.float32

In [ ]:
a = torch.FloatTensor(4,5)
b = torch.FloatTensor([[2,3], [4,5]])
a

tensor([[-5.2008e+02,  1.8665e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
b

tensor([[2., 3.],
        [4., 5.]])

In [ ]:
a.dtype

torch.float32

In [ ]:
b.dtype

torch.float32

In [ ]:
a = torch.IntTensor(4,5)
b = torch.IntTensor([[2,3], [4,5]])

In [ ]:
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
b

tensor([[2, 3],
        [4, 5]], dtype=torch.int32)

In [ ]:
y = a+z
y

tensor([[-5.1603e+02,  1.8665e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
y.dtype

torch.float32

In [ ]:
torch.add(a,z)

tensor([[-5.1603e+02,  1.8665e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
a = torch.rand(4,5)
a

tensor([[0.7299, 0.4119, 0.1586, 0.6938, 0.7291],
        [0.7340, 0.1405, 0.9688, 0.2492, 0.2974],
        [0.4185, 0.3134, 0.5664, 0.9640, 0.5582],
        [0.2418, 0.3175, 0.5506, 0.6550, 0.8595]])

In [ ]:
a.dtype

torch.float32

In [ ]:
b = a.numpy()

In [ ]:
b

array([[0.729867  , 0.41193742, 0.15862745, 0.6937547 , 0.72905344],
       [0.73404735, 0.14054167, 0.96877086, 0.2491774 , 0.2974339 ],
       [0.41848338, 0.31340033, 0.56637716, 0.9639789 , 0.55823827],
       [0.24182934, 0.317527  , 0.550611  , 0.6549638 , 0.85949254]],
      dtype=float32)

In [ ]:
import numpy as np

In [ ]:
a = np.ones(5)
b = torch.from_numpy(a)
a

array([1., 1., 1., 1., 1.])

In [ ]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [ ]:
a

array([2., 2., 2., 2., 2.])

In [ ]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [ ]:
c = b + torch.tensor([1,2,3,4,5])
c

tensor([3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
c = c.float()
c.dtype

torch.float32

In [ ]:
c = c.double()
c.dtype

torch.float64

In [ ]:
c = c.int()
c

tensor([3, 4, 5, 6, 7], dtype=torch.int32)

In [ ]:
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [ ]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
y = torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
y = torch.squeeze(y,2)
y.size()

torch.Size([2, 2, 2])

In [ ]:
torch.abs(torch.tensor([-1,-2,3]))

tensor([1, 2, 3])

In [ ]:
a = torch.randn(4)
a

tensor([-1.8752,  0.1707, -0.1730, -0.9479])

In [ ]:
b = torch.add(a, 20)
b

tensor([18.1248, 20.1707, 19.8270, 19.0521])

In [ ]:
c = torch.mul(a,0.1)
c

tensor([-0.1875,  0.0171, -0.0173, -0.0948])

In [ ]:
d = torch.mul(a,b)
d

tensor([-33.9878,   3.4426,  -3.4296, -18.0587])

In [ ]:
x = torch.rand(2,3)
y = torch.rand(3,2)
x

tensor([[0.6851, 0.2959, 0.2037],
        [0.8503, 0.8144, 0.5426]])

In [ ]:
y

tensor([[0.8805, 0.3495],
        [0.9663, 0.8681],
        [0.4352, 0.7617]])

In [ ]:
d = torch.matmul(x,y)
d

tensor([[0.9778, 0.6515],
        [1.7718, 1.4174]])

In [ ]:
d = torch.matmul(y,x)
d

tensor([[0.9004, 0.5451, 0.3690],
        [1.4002, 0.9929, 0.6679],
        [0.9459, 0.7491, 0.5019]])

In [ ]:
y.size()

torch.Size([3, 2])

In [ ]:
k = y.mean()
k.data.dtype

torch.float32

In [ ]:
torch.mean(y)

tensor(0.7102)

In [ ]:
y

tensor([[0.8805, 0.3495],
        [0.9663, 0.8681],
        [0.4352, 0.7617]])

In [ ]:
torch.mean(y,0)

tensor([0.7607, 0.6598])

In [ ]:
torch.mean(y,1)

tensor([0.6150, 0.9172, 0.5985])

In [ ]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[1,1],[4,4]])
x

tensor([[1, 2],
        [3, 4]])

In [ ]:
y

tensor([[1, 1],
        [4, 4]])

In [ ]:
torch.eq(x,y)

tensor([[ True, False],
        [False,  True]])

In [ ]:
torch.equal(x,y)

False

In [ ]:
torch.equal(y,y)

True

In [ ]:
torch.ge(x,y)

tensor([[ True,  True],
        [False,  True]])

In [ ]:
torch.le(x,y)

tensor([[ True, False],
        [ True,  True]])

In [ ]:
torch.gt(x,y)

tensor([[False,  True],
        [False, False]])

In [ ]:
torch.lt(x,y)

tensor([[False, False],
        [ True, False]])